[program.Test]
command = "/usr/bin/ls"
chdir = "./config-parser"
chmod = "111"
process_count = 3
auto_start = true
restart_protocol = "never"
exit_codes = [100, 2]
runtime = 5
restart_count = 3
exit_signal = "TERM"
kill_time = 10
stdin = "stdin"
stdout = "stdout"
env = []